### ISSUE TITLE
TypeError after `ssdp:send-message` event

### ISSUE THREAD

**Issue by blotto** [achingbrain/ssdp#1]
Hey @achingbrain was exploring your examples and cannot get past the send-message event with the following code:

```
var usn = 'urn:schemas-upnp-org:service:ContentDirectory:1';

bus.on('transport:outgoing-message', function (socket, message, remote) {
    console.info('-> Outgoing to %s:%s via %s', remote.address, remote.port, socket.type)
    //console.info(message.toString('utf8'))
});

bus.on('*', function(message) {
    // receive a notification about a service
    console.info(message.toString('utf8'))
});

bus.on('error', console.error);
```
produces
```
-> Outgoing to 239.255.255.250:1900 via udp4
transport:outgoing-message
ssdp:send-message
TypeError: Cannot read property 'then' of undefined
    at SSDP.<anonymous> (/Users/nick/Dev/ssdp/lib/index.js:43:13)
    at SSDP.on (/Users/nick/Dev/ssdp/node_modules/wildemitter/wildemitter.js:50:18)
    at SSDP.prototype.emit (/Users/nick/Dev/ssdp/node_modules/wildemitter/wildemitter.js:117:30)
    at SSDP.createSockets.then.sockets (/Users/nick/Dev/ssdp/lib/index.js:86:12)
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:160:18)
    at node.js:449:3
error

```

Looking at the stack trace, its not clear to me why the proxy method fails here. Anything I am doing wrong?

Cheers!

**Comment by achingbrain** [comment]
You're doing nothing wrong, it's a bug :(

I've pushed version 2.1.1 to npm, it should resolve the issue, please give it a go..

**Comment by blotto** [comment]
Thanks for the quick response! Pulled. So I am getting the `ready` event fired now. 👍   And see a response come back from my Roku device within Wireshark. In this case, I'm looking for DIAL services `urn:dial-multiscreen-org:service:dial:1`.  However, I would expect to see `transport:incoming-message` event now, but 0 services are discovered.

client :    10.0.1.99	        239.255.255.250	SSDP	M-SEARCH * HTTP/1.1 
service : 10.0.1.113	10.0.1.99	                SSDP	HTTP/1.1 200 OK

**Comment by achingbrain** [comment]
Interesting. Could you share a pcap dump from wireshark?

**Comment by blotto** [comment]
this shows the outgoing message and response (ssdp packets only)

[ssdp_packets_only.pcapng.zip](https://github.com/achingbrain/ssdp/files/679813/ssdp_packets_only.pcapng.zip)

**Comment by achingbrain** [comment]
I'm assuming you've set up the extra listeners as per [here](https://github.com/achingbrain/ssdp/blob/master/test/fixtures/all.js) - do you see a `transport:incoming-message` event at all?

From the Roku's search response in the pcapng file, it looks like it should get parsed, in which case the next thing the node process would is request the definition file from http://10.0.1.113:8060/dial/dd.xml - in wireshark do you see this request being made?

**Comment by blotto** [comment]
Yeah those listeners are in place as well as a wildcard listener to capture anything.  I do not see a call from the client back to roku for the definition file however. I gravitated toward the ports, at first I noticed Chrome taking the default port (for chromecast), killed that and see port 1900 in use now. But that didnt have any impact to this.  I'll dig deeper today and see what I can find.  ~Cheers

**Comment by blotto** [comment]
best I can conclude is the 'message' event from the underlying socket is never fired.  closing issue since you resolved the original issue.  I doubt this is related and may be something else outside of your project. i'll let you know if i find anything.  thanks for your help!

**Comment by blotto** [comment]
FWIW, turned out the firewall on Mac blocked the incoming messages. Works great now.

**Comment by achingbrain** [comment]
Aha, glad you got it sorted
